[versions]
agp = "8.12.3"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
appcompat = "1.7.1"
material = "1.13.0"
compose = "1.6.8"
kotlinx-coroutines = "1.10.2"
detekt = "1.23.6"
serialization = "1.7.3"

# DI
koin = "4.1.1"
ksp = "2.0.21-1.0.27"
#ksp = "2.2.10-2.0.2"

# Architecture
mvikotlin = "4.0.0"
decompose = "3.1.0"
essenty = "2.1.0"

# UI
coil = "2.7.0"

# Network
retrofit = "2.11.0"
okhttp = "4.12.0"

# DB
room = "2.6.1"

datastore = "1.2.0"

# Security
secretsGradlePlugin = "2.0.1"

# Firebase
firebase-messaging = "24.1.1"
firebase-crashlytics = "19.4.3"
firebase-analytics = "22.4.0"
firebase-remote-config = "22.1.2"
firebase-perfomance = "21.0.4"
crashlytics-plugin = "3.0.3"
perfomance-plugin = "1.4.2"
google-services = "4.4.2"

# Testing
mockk = "1.13.10"
coroutines-test = "1.10.2"

# Android SDK
minSdk = "26"
targetSdk = "36"
compileSdk = "36"
jetbrainsKotlinJvm = "2.0.21"
material3 = "1.4.0"
runtime = "1.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
androidx-compose-icons = { group = "androidx.compose.material", name ="material-icons-extended", version.ref ="compose" }

# DI / Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Extra
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

coil-network-okhttp = { group = "io.coil-kt", name = "coil-network-okhttp", version.ref = "coil" }


mvikotlin-core = { group = "com.arkivanov.mvikotlin", name = "mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { group = "com.arkivanov.mvikotlin", name ="mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }


arch-decompose = { group = "com.arkivanov.decompose", name ="decompose", version.ref = "decompose" }
arch-decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
arch-essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
arch-essenty-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }
arch-essenty-statekeeper = { group = "com.arkivanov.essenty", name = "state-keeper", version.ref = "essenty" }


retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Unit testing
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }


# Firebase
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging" }
firebase-crashlytics =  { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebase-analytics" }
firebase-remote-config =  { group = "com.google.firebase", name = "firebase-config", version.ref = "firebase-remote-config" }
firebase-perfomance = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebase-perfomance" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }


# Google / Firebase плагины
google-services = { id = "com.google.gms.google-services", version.ref = "google-services"}
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-plugin"}
perfomance = { id = "com.google.firebase.firebase-perf", version.ref = "perfomance-plugin" }
